version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
    nodejs: "16"

sphinx:
  fail_on_warning: false

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

formats:
  - pdf
  - epub
