version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - bash pip install git+https://github.com/jbms/sphinx-immaterial.git
sphinx:
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .

formats:
  - pdf
  - epub
